apiVersion: v1
kind: Pod
metadata:
  name: envars-pod
spec:
  containers:
    - name: envars-pod
      args:
        - while true; do echo -en '\n'; printf UNCHANGED_REFERENCE=$UNCHANGED_REFERENCE'\n'; printf SERVICE_ADDRESS=$SERVICE_ADDRESS'\n';printf ESCAPED_REFERENCE=$ESCAPED_REFERENCE'\n'; sleep 60; done;
      command:
        - sh
        - -c
      image: busybox
      env:
        - name: SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: urlconfig000
              key: port
        - name: SERVICE_IP
          valueFrom:
            configMapKeyRef:
              name: urlconfig000
              key: ip
        - name: UNCHANGED_REFERENCE
          value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
        - name: PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: urlconfig000
              key: protocol
        - name: SERVICE_ADDRESS
          value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
        - name: ESCAPED_REFERENCE
          value: "$$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"